### ISSUE TITLE
Game Details

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#4]
# Game Details

## Value Proposition

**As a user**

**I want to** access detailed information about each game,

**so that** I can understand the requirements and context better.

## Description

![Image](https://github.com/user-attachments/assets/f715ae28-db04-4d9b-bc32-930a16e4390d)

## Acceptance Criteria

- Each game in the game list has a link to a details page.
- Each details page contains:
  - title
  - description
  - rating
- The detailed view includes a “back” link, allowing users to easily navigate back to the list of games.

## Tasks

- Create Feature Branch `feature/game-details`
- Add routes for the game list and game details pages: `/page/[id].js`
- Display the list of games with links to the details pages. 
- Import Router method/function
- Create a handler in `/page/[id]/index.js`
- Display the game title, description, and rating.
- Add a “Back” button/link to navigate back to the game list.

**Comment by NikRoe** [comment]
Hi there,

nice work!

The Acceptance Criteria still mention `Due date` and `Priority level`. You most likely want to change one of them to `Rating` and remove the other.

And do you also want to display the current progress of the game within the detail view? It might make sense from a user perspective, since otherwise you would always need to navigate back to the list to see what the progress for the respective game is.

**Comment by DBr-git** [comment]
Updated to remove Due date and Priority and added rating.

Current progress gets added to the detail view at a later user story `Mark game as complete` to not have to take extra steps to first implement it as a simple displayed value to later displaying it in a dropdown menu where you can change it

**Comment by NikRoe** [comment]
Sounds good, approved 👌 ✅
